### ISSUE TITLE
functions framework with google pub/sub emulator

### ISSUE THREAD

**Issue by baldrich-randori** [GoogleCloudPlatform/functions-framework-python#74] opened 2020-07-28 22:21 UTC
I am attempting to replicate our cloud functions locally but they all leverage pub/sub. I can easily use the pub/sub emulator but I don't see how to subscribe to a topic on the local emulator using the local cloud functions? Am I missing something, how would you be able to run this locally and emulate your workflow without this? 

Would anyone have any recommendations on how to run the full stack locally for local development environments? 

I was assuming I would be able to set the pub/sub emulator env var and the cloud function would automatically subscribe and pull like it does in our testing and production envs.

Thanks for the help!

**Comment by di** [comment] 2020-07-29 15:12
Hi @baldrich-randori, thanks for reporting this issue.

The framework is not currently compatible with the Pub/Sub emulator (see #23). Once it is, we will document how to use them together.

Closing as a duplicate of #23.

**Closed by di** 2020-07-29 15:12 UTC
