### ISSUE TITLE
[Feature Request] Continue to run even if introduce syntax errors

### ISSUE THREAD

**Issue by ALiangLiang** [GoogleCloudPlatform/functions-framework-python#135] opened 2021-07-03 08:54 UTC
If I used native `flask run` to launch a functions as a server, it will keep running even though I raise a syntax error. But functions-framework can't. Is there a way to implement this mechanism in this nice tool? It's annoying to always re-command manually.

I survey how flask works with it and found an [article](https://flask.palletsprojects.com/en/2.0.x/server/?highlight=syntax#lazy-or-eager-loading) about this mechanism.

**Comment by di** [comment] 2021-07-07 17:58
This is a bit tricky, because the execution of the user-supplied source happens before the Flask development server is started, during the creation of the WSGI app: https://github.com/GoogleCloudPlatform/functions-framework-python/blob/c7f66fd5ed9856bdf4e484774742d7c158ab7b43/src/functions_framework/__init__.py#L237

This means that we haven't started Flask's reloader yet and don't have access to another reloader. We'd need to manually catch any exceptions and raise them to the user in a reloader loop, but ideally one that's able to watch the filesystem for changes so as not to constantly be executing the module.

I agree that this can be annoying though, so I'll leave this open for now and see if we can find a better solution.

**Comment by ALiangLiang** [comment] 2021-07-07 18:22
I see. Indeed, it's a complex problem. Maybe you can provide a shell script workaround to auto re-launch `functions-framwork` on doc or example?

**Comment by josephlewis42** [comment] 2023-03-03 21:51
This looks like a duplicate of #213

**Closed by josephlewis42** 2023-03-03 21:51 UTC
Labels: enhancement
