### ISSUE TITLE
Error when following Quickstart: Pub/Sub emulator

### ISSUE THREAD

**Issue by leo-padron** [GoogleCloudPlatform/functions-framework-python#177] opened 2022-03-11 03:00 UTC
I'm following the instructions exactly as described in 
**Functions Framework for Python**
-Quickstart: Pub/Sub emulator

But I run these steps:

![image](https://user-images.githubusercontent.com/71105287/157793744-2e1ab130-00c8-4c6c-9d28-adf3b5461a53.png)

I get this error:

![image](https://user-images.githubusercontent.com/71105287/157793857-4e5feaa0-0b0b-4826-bed7-fe0c836ef5c7.png)

**Comment by grant** [comment] 2022-03-18 21:21
This is not parsing the command correctly.

I think you need to write `"create-push"` instead of `create-push` for this to work properly.

**Comment by grant** [comment] 2022-04-01 21:48
Part of docs: https://github.com/GoogleCloudPlatform/functions-framework-python#quickstart-pubsub-emulator

@anguillanneuf, can you triage this issue since you added these docs?

**Comment by anguillanneuf** [comment] 2022-04-21 21:37
@leo-padron I wasn't able to reproduce the error you are seeing. 

This is what I get:

```
tianzi 14:32 snippets % python subscriber.py tz-playground-bigdata create-push one yiyi http://localhost:8080          (main)
Push subscription created: name: "projects/tz-playground-bigdata/subscriptions/yiyi"
topic: "projects/tz-playground-bigdata/topics/one"
push_config {
  push_endpoint: "http://localhost:8080"
}
ack_deadline_seconds: 10
message_retention_duration {
  seconds: 604800
}
.
Endpoint for subscription is: http://localhost:8080
```

I suspect $TOPIC_ID and $PUSH_SUBSCRIPTION_ID aren't populated in your case. Could you check? Thanks for your patience.

**Comment by BoHuang2018** [comment] 2022-04-22 08:04
I have a question for [the paragraph of using **PubSub Emulator** ](https://github.com/GoogleCloudPlatform/functions-framework-python/#quickstart-pubsub-emulator)

Above the example function, `def hello(event, context):`, there is no decorator like `@functions_framework.cloud_event`. 

@leo-padron  Is this the reason for your error ?

**Comment by grant** [comment] 2022-05-31 17:21
There is no decorator for `event`, just `cloud_event` - which is preferred.

I'm going to close this as both Tianzi and myself couldn't repro the issue and I believe there's just a user-error typo.

**Closed by grant** 2022-05-31 17:21 UTC
