### ISSUE TITLE
Deploying Cloud Function gives error: MissingTargetException

### ISSUE THREAD

**Issue by bhandari-nitin** [GoogleCloudPlatform/functions-framework-python#157] opened 2021-10-19 17:04 UTC
Hi there,

Deploying google cloud function with python3.8 runtime gives error:

```
MissingTargetException: File /workspace/main.py is expected to contain a function named main
.create_app ( /layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py:259 )
```

Stacktrace

```
functions_framework.exceptions.MissingTargetException: File /workspace/main.py is expected to contain a function named main
at create_app (/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py:259)
at _cli (/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/_cli.py:37)
at invoke (/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py:763)
at invoke (/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py:1404)
at main (/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py:1062)
at __call__ (/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py:1137)
at <module> (/layers/google.python.pip/pip/bin/functions-framework:8)
```

There is a main function within main.py that I am trying to deploy.

**Comment by di** [comment] 2021-10-19 17:08
Hi, can you share your `main.py` file (or at least the signature of the function you're trying to deploy) as well as the command you're using to deploy?

**Comment by di** [comment] 2021-10-19 18:22
I created a new Python 3.8 function by pasting that into the UI at https://console.cloud.google.com/functions/add, changing the entrypoint from `hello_world` to `main`,  and was able to successfully deploy it.

Any other details you can give us? Have you set any environment variables or otherwise changed the function configuration?

Can you go to the "Source" tab for the function and select "Download Zip" and upload it here?

**Comment by bhandari-nitin** [comment] 2021-10-19 18:34
I see, strange. I tried the same with only the code  I shared and got same error. 

Here are the details:

1. Region: US-Central1
2. Trigger: HTTP
3. Runtime: Python3.8
4. Memory Allocated: 256 MB
5. Executed Function: main
6. Authentication: <Blank though Allow Unauthenticated was selected>


Zip file:
[function-source.zip](https://github.com/GoogleCloudPlatform/functions-framework-python/files/7375863/function-source.zip)

**Comment by grant** [comment] 2022-06-10 16:32
Reading through this thread... it seems like we've figured out a way to deploy successfully. Not sure if there is an issue with the Functions Framework.

I'm going to close this, but if the issue is still persisting, please open a new issue and link this issue in the description.

**Closed by grant** 2022-06-10 16:32 UTC
