### ISSUE TITLE
Unable to use functions-framework-python with pubsub beta emulator

### ISSUE THREAD

**Issue by akssinhaamit** [GoogleCloudPlatform/functions-framework-python#73] opened 2020-07-20 09:00 UTC
Following the [README.md](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/40/files), I am able to trigger functions but I am expecting 'data' as a part of the event but unfortunately the message being passed from `google beta emulatar` is in the following format:
```
{
      "subscription": "projects/test/subscriptions/test1",
      "message": {
        "data": "TWVzc2FnZSBudW1iZXIgNA==",
        "messageId": "4",
        "attributes": {}
      },
      "id": 3
    }
```
Is there something I am missing? Please guide!

**Comment by di** [comment] 2020-07-20 14:28
Thanks for the report. This is a duplicate of https://github.com/GoogleCloudPlatform/functions-framework-python/issues/23.

**Closed by di** 2020-07-20 14:28 UTC
